import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <h4>Hikari Open Source</h4>
        <p>
          an open source project built to <br />
          make useful applications
        </p>
        <p className="list">Awaseru</p>
        Coming Soon...
      </div>
    </div>
  );
};

export default Home;
